// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4uQH-YL_rv-vkXhNQE_7IlUI1A_FT8ws',
    appId: '1:492451770445:web:5c132250fe2bf7d0772c04',
    messagingSenderId: '492451770445',
    projectId: 'water-quality-detection-5ab50',
    authDomain: 'water-quality-detection-5ab50.firebaseapp.com',
    databaseURL: 'https://water-quality-detection-5ab50-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'water-quality-detection-5ab50.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ0MOOuWDBwyKJdgEhBP52xYmTN9cL8QI',
    appId: '1:492451770445:android:367a1efcf20542c8772c04',
    messagingSenderId: '492451770445',
    projectId: 'water-quality-detection-5ab50',
    databaseURL: 'https://water-quality-detection-5ab50-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'water-quality-detection-5ab50.appspot.com',
  );
}
